import type {
  DimensionKey,
  DimensionAssessment,
  Stakeholder,
  SolutionCard,
  PlanTask,
  KPI,
} from '../types';

export const sampleDimensions: Record<DimensionKey, DimensionAssessment> = {
  socioCultural: { tools: 1, data: 1, culture: 2 },
  teachingLearning: { tools: 2, data: 1, culture: 1 },
  academicManagement: { tools: 1, data: 1, culture: 1 },
  administrativeManagement: { tools: 1, data: 0, culture: 0 },
  researchInnovation: { tools: 2, data: 1, culture: 1 },
  digitalGovernance: { tools: 1, data: 0, culture: 1 },
  institutionalImage: { tools: 2, data: 1, culture: 1 },
  universityExtension: { tools: 1, data: 0, culture: 0 },
};

export const sampleStakeholders: Stakeholder[] = [
  {
    id: 'sample-s1',
    group_id: '',
    name: 'Faculty of Information Technology',
    role: 'Professors',
    discipline: 'STEM',
    power: 'low',
    interest: 'high',
    behavior: 'supportive',
    anxiety: 'ethical_engagement',
    missing_lever: 'relative_advantage',
    notes: 'Already using LMS and some AI grading tools. Keen to expand.',
  },
  {
    id: 'sample-s2',
    group_id: '',
    name: 'Humanities & Social Sciences Department',
    role: 'Professors',
    discipline: 'Humanities',
    power: 'low',
    interest: 'low',
    behavior: 'subtle_avoiding',
    anxiety: 'displacement',
    missing_lever: 'compatibility',
    notes: 'Fear AI will devalue critical thinking and essay writing.',
  },
  {
    id: 'sample-s3',
    group_id: '',
    name: 'Administrative Staff (Registrar)',
    role: 'Administration',
    power: 'low',
    interest: 'high',
    behavior: 'pronounced_opposing',
    anxiety: 'learning',
    missing_lever: 'low_complexity',
    notes: 'Overwhelmed by current workload, sees AI as extra burden.',
  },
  {
    id: 'sample-s4',
    group_id: '',
    name: 'Undergraduate Students (Year 1-2)',
    role: 'Students',
    power: 'low',
    interest: 'high',
    behavior: 'supportive',
    anxiety: 'learning',
    missing_lever: 'low_complexity',
    notes: 'Gen Z, tech-savvy, already using ChatGPT informally.',
  },
  {
    id: 'sample-s5',
    group_id: '',
    name: 'Vice-Rector for Academic Affairs',
    role: 'Direction',
    power: 'high',
    interest: 'high',
    behavior: 'supportive',
    anxiety: 'sociotechnical',
    missing_lever: 'relative_advantage',
    notes: 'Supportive in principle but needs concrete ROI evidence.',
  },
];

export const sampleSolutions: SolutionCard[] = [
  {
    id: 'sample-sol1',
    group_id: '',
    name: 'Welcome Guide Chatbot',
    target: 'Students',
    difficulty: 'Low',
    status: 'Prototyped',
    problem_solved: 'Answer new students\' questions about campus, rules, and procedures',
    vibe_coding_notes: 'Uploaded student handbook PDF as context in Google AI Studio. Works well for factual questions. Needs guardrails for off-topic queries.',
    platform_used: 'Google AI Studio',
    assigned_phase: 1,
    sort_order: 0,
  },
  {
    id: 'sample-sol2',
    group_id: '',
    name: 'Syllabus Generator',
    target: 'Professors',
    difficulty: 'Low',
    status: 'Planned',
    problem_solved: 'Generate a structured syllabus from a course description — saves hours of formatting',
    assigned_phase: 1,
    sort_order: 1,
  },
  {
    id: 'sample-sol3',
    group_id: '',
    name: 'Email Drafter',
    target: 'Administration',
    difficulty: 'Low',
    status: 'Planned',
    problem_solved: 'Draft official communications from bullet points — consistent tone, bilingual (Vietnamese/English)',
    assigned_phase: 1,
    sort_order: 2,
  },
];

export const sampleTasks: PlanTask[] = [
  // Phase 1 — Activation (Days 1-30)
  {
    id: 'sample-t1',
    group_id: '',
    name: 'Secure rector approval for AI adoption policy',
    phase: 1,
    champion_name: 'Vice-Rector Tran Minh',
    champion_target: 'Administration',
    priority: 'High',
    status: 'Not Started',
    sort_order: 0,
  },
  {
    id: 'sample-t2',
    group_id: '',
    name: 'Pilot Welcome Guide Chatbot with 200 freshmen',
    phase: 1,
    champion_name: 'Dr. Le Thi Hoa',
    champion_target: 'Students',
    priority: 'High',
    status: 'Not Started',
    source_solution_id: 'sample-sol1',
    sort_order: 1,
  },
  {
    id: 'sample-t3',
    group_id: '',
    name: 'Set up AI tools training calendar for faculty',
    phase: 1,
    champion_name: 'Prof. Pham Van Duc',
    champion_target: 'Professors',
    priority: 'Medium',
    status: 'Not Started',
    sort_order: 2,
  },
  // Phase 2 — Implementation (Days 31-60)
  {
    id: 'sample-t4',
    group_id: '',
    name: 'Deploy Syllabus Generator for 5 pilot departments',
    phase: 2,
    champion_name: 'Prof. Pham Van Duc',
    champion_target: 'Professors',
    priority: 'High',
    status: 'Not Started',
    source_solution_id: 'sample-sol2',
    sort_order: 3,
  },
  {
    id: 'sample-t5',
    group_id: '',
    name: 'Run AI literacy workshop for admin staff',
    phase: 2,
    champion_name: 'Dr. Le Thi Hoa',
    champion_target: 'Administration',
    priority: 'Medium',
    status: 'Not Started',
    sort_order: 4,
  },
  // Phase 3 — Institutionalization (Days 61-90)
  {
    id: 'sample-t6',
    group_id: '',
    name: 'Review KPIs and draft sustainability plan',
    phase: 3,
    champion_name: 'Vice-Rector Tran Minh',
    champion_target: 'Administration',
    priority: 'High',
    status: 'Not Started',
    sort_order: 5,
  },
  {
    id: 'sample-t7',
    group_id: '',
    name: 'Present results to university board',
    phase: 3,
    champion_name: 'Vice-Rector Tran Minh',
    champion_target: 'Administration',
    priority: 'Medium',
    status: 'Not Started',
    sort_order: 6,
  },
];

export const sampleKpis: KPI[] = [
  {
    id: 'sample-k1',
    group_id: '',
    name: '% of courses using at least one AI tool',
    type: 'Leading',
    target: '15% by Day 30, 40% by Day 90',
    data_source: 'LMS usage analytics',
    responsible: 'VP Academic Affairs',
    phase: 1,
  },
  {
    id: 'sample-k2',
    group_id: '',
    name: 'Student satisfaction with AI tools (NPS)',
    type: 'Lagging',
    target: '8+/10 average',
    data_source: 'Post-pilot survey',
    responsible: 'Office of Student Success',
    phase: 3,
  },
  {
    id: 'sample-k3',
    group_id: '',
    name: 'Faculty AI training completion rate',
    type: 'Leading',
    target: '70% of target faculty by Day 60',
    data_source: 'Training attendance records',
    responsible: 'HR & Faculty Development',
    phase: 2,
  },
  {
    id: 'sample-k4',
    group_id: '',
    name: 'Reduction in repetitive admin queries',
    type: 'Lagging',
    target: '-50% vs. baseline',
    data_source: 'Helpdesk ticket count',
    responsible: 'Registrar Office',
    phase: 3,
  },
];
